server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: transaction-service
  
  datasource:
    url: jdbc:sqlite:${DATABASE_PATH:../financial_transactions.db}
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# External service configuration
user-service:
  base-url: ${USER_SERVICE_URL:http://localhost:8081/api/v1}
  timeout: 5000

# Logging
logging:
  level:
    ch.innovation.ai.tools.demo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
