server:
  port: 8081
spring:
  datasource:
    url: jdbc:sqlite:./demo-users.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
module2:
  base-url: http://localhost:8082
